import type { RuleSet } from './types'

export const PRESETS: Record<string, RuleSet> = {
  Default: {
    fileRules: [
      { extension: '.png',  folder: 'image' },
      { extension: '.jpg',  folder: 'image' },
      { extension: '.jpeg', folder: 'image' },
      { extension: '.psd',  folder: 'image' },
      { extension: '.mp4',  folder: 'video' },
      { extension: '.mkv',  folder: 'video' },
      { extension: '.avi',  folder: 'video' },
      { extension: '.mov',  folder: 'video' },
      { extension: '.wmv',  folder: 'video' },
      { extension: '.zip',  folder: 'zip' },
      { extension: '.rar',  folder: 'zip' },
      { extension: '.exe',  folder: 'exe' },
      { extension: '.msi',  folder: 'exe' },
      { extension: '.pdf',  folder: 'pdf' },
      { extension: '.mp3',  folder: 'sound' },
      { extension: '.wav',  folder: 'sound' },
      { extension: '.ogg',  folder: 'sound' },
      { extension: '.flac', folder: 'sound' },
      { extension: '.m4a',  folder: 'sound' },
      { extension: '.iso',  folder: 'os' },
      { extension: '.img',  folder: 'os' },
      { extension: '.gif',  folder: 'gif' },
      { extension: '.webp', folder: 'gif' },
      { extension: '.apng', folder: 'gif' },
      { extension: '.avif', folder: 'gif' },
      { extension: '.ttf',  folder: 'font' },
      { extension: '.otf',  folder: 'font' },
      { extension: '.ttc',  folder: 'font' },
    ],
    prefixRules: [],
    folderRules: [],
  },
  Developer: {
    fileRules: [
      { extension: '.png',  folder: 'image' },
      { extension: '.jpg',  folder: 'image' },
      { extension: '.jpeg', folder: 'image' },
      { extension: '.mp4',  folder: 'video' },
      { extension: '.zip',  folder: 'zip' },
      { extension: '.rar',  folder: 'zip' },
      { extension: '.exe',  folder: 'exe' },
      { extension: '.msi',  folder: 'exe' },
      { extension: '.pdf',  folder: 'pdf' },
      { extension: '.json', folder: 'config' },
      { extension: '.yml',  folder: 'config' },
      { extension: '.yaml', folder: 'config' },
      { extension: '.md',   folder: 'docs' },
      { extension: '.sh',   folder: 'scripts' },
      { extension: '.bat',  folder: 'scripts' },
      { extension: '.log',  folder: 'logs' },
      { extension: '.ttf',  folder: 'font' },
      { extension: '.otf',  folder: 'font' },
    ],
    prefixRules: [],
    folderRules: [],
  },
  Designer: {
    fileRules: [
      { extension: '.png',    folder: 'image' },
      { extension: '.jpg',    folder: 'image' },
      { extension: '.jpeg',   folder: 'image' },
      { extension: '.psd',    folder: 'design' },
      { extension: '.ai',     folder: 'design' },
      { extension: '.sketch', folder: 'design' },
      { extension: '.fig',    folder: 'design' },
      { extension: '.svg',    folder: 'vector' },
      { extension: '.gif',    folder: 'gif' },
      { extension: '.webp',   folder: 'gif' },
      { extension: '.mp4',    folder: 'video' },
      { extension: '.mov',    folder: 'video' },
      { extension: '.ttf',    folder: 'font' },
      { extension: '.otf',    folder: 'font' },
      { extension: '.ttc',    folder: 'font' },
      { extension: '.zip',    folder: 'zip' },
      { extension: '.pdf',    folder: 'pdf' },
    ],
    prefixRules: [],
    folderRules: [],
  },
  Media: {
    fileRules: [
      { extension: '.png',  folder: 'image' },
      { extension: '.jpg',  folder: 'image' },
      { extension: '.jpeg', folder: 'image' },
      { extension: '.psd',  folder: 'image' },
      { extension: '.gif',  folder: 'gif' },
      { extension: '.webp', folder: 'gif' },
      { extension: '.apng', folder: 'gif' },
      { extension: '.avif', folder: 'gif' },
      { extension: '.mp4',  folder: 'video' },
      { extension: '.mkv',  folder: 'video' },
      { extension: '.avi',  folder: 'video' },
      { extension: '.mov',  folder: 'video' },
      { extension: '.wmv',  folder: 'video' },
      { extension: '.mp3',  folder: 'sound' },
      { extension: '.wav',  folder: 'sound' },
      { extension: '.ogg',  folder: 'sound' },
      { extension: '.flac', folder: 'sound' },
      { extension: '.m4a',  folder: 'sound' },
    ],
    prefixRules: [],
    folderRules: [],
  },
  Minimal: {
    fileRules: [
      { extension: '.png',  folder: 'image' },
      { extension: '.jpg',  folder: 'image' },
      { extension: '.jpeg', folder: 'image' },
      { extension: '.mp4',  folder: 'video' },
      { extension: '.mkv',  folder: 'video' },
      { extension: '.avi',  folder: 'video' },
      { extension: '.mov',  folder: 'video' },
    ],
    prefixRules: [],
    folderRules: [],
  },
}

export const PRESET_NAMES = Object.keys(PRESETS) as (keyof typeof PRESETS)[]
